# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

def shared_pods
  use_react_native!(:hermes_enabled => false)
  pod 'OktaOidc', :git => 'https://github.com/longvt96/okta-oidc-ios', :branch => 'master'
end

target 'ReactNativeOktaSdkBridge' do
  shared_pods
end

target 'Tests' do
  shared_pods
end
